version: "2"

services:
  fadubackend:
    build: .
    container_name: fadu-backend
    ports:
      - 5000:5000
    env_file:
      - .env
    # restart: always # for production this is useful
    depends_on:
      - cache

  cache:
    image: memcached:1.6
