version: "2"

networks:
  faduviva:
    external: true

services:
  fadubackend:
    build: .
    container_name: fadu-backend
    ports:
      - 5000:5000
    env_file:
      - .env
    # restart: always # for production this is useful
    depends_on:
      - cache
    networks:
      - faduviva

  cache:
    image: memcached:1.6
    networks:
      - faduviva
