from layers.domain.bus.base import BusEndingStop

CIUDAD_UNIVERSITARIA_BUS_ENDING_STOPS = [
    BusEndingStop(route_id='305', direction=0),
    BusEndingStop(route_id='327', direction=1),
    BusEndingStop(route_id='1750', direction=1),
    BusEndingStop(route_id='265', direction=1),
    BusEndingStop(route_id='203', direction=0),
    BusEndingStop(route_id='304', direction=0),
    BusEndingStop(route_id='1744', direction=1),
    BusEndingStop(route_id='263', direction=1),
    BusEndingStop(route_id='1748', direction=1),
    BusEndingStop(route_id='455', direction=0),
    BusEndingStop(route_id='79', direction=0),
    BusEndingStop(route_id='102', direction=0),
    BusEndingStop(route_id='326', direction=1),
    BusEndingStop(route_id='276', direction=0),
    BusEndingStop(route_id='266', direction=1),
    BusEndingStop(route_id='78', direction=0),
    BusEndingStop(route_id='273', direction=0),
    BusEndingStop(route_id='83', direction=0),
    BusEndingStop(route_id='1747', direction=1),
    BusEndingStop(route_id='264', direction=1),
    BusEndingStop(route_id='469', direction=1),
    BusEndingStop(route_id='1742', direction=1),
    BusEndingStop(route_id='1801', direction=0),
    BusEndingStop(route_id='81', direction=0),
    BusEndingStop(route_id='274', direction=0),
    BusEndingStop(route_id='443', direction=0),
    BusEndingStop(route_id='269', direction=1),
    BusEndingStop(route_id='275', direction=0),
    BusEndingStop(route_id='101', direction=0),
]
